spring:
  datasource:
    url : jdbc:mysql://localhost:3306/teamdb?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : abok1234
    driver-class-name: com.mysql.cj.jdbc.Driver
