spring:
  datasource:
    url : jdbc:mysql://localhost:3306/데이터베이스_이름?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
